name: Auto-promote Claude branch to main
on:
  push:
    branches:
      - "claude/**"
permissions:
  contents: write
jobs:
  promote:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout full history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: Merge branch into main
        env:
          BRANCH: ${{ github.ref_name }}
        run: |
          git fetch origin main
          git checkout main
          git merge --no-ff "$BRANCH" -m "auto: promote $BRANCH into main"
          git push origin main
